world:
  name: Мир
  cooldown: 120 # Раз в это время будет заспавнен груз. В минутах
  ignored-worlds:
    - hub
world_the_end:
  name: Хаб
  cooldown: 65
  ignored-worlds:
    - world_nether
    - hub